
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - demo.demo.operator.io
  resources:
  - demooperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.demo.operator.io
  resources:
  - demooperators/finalizers
  verbs:
  - update
- apiGroups:
  - demo.demo.operator.io
  resources:
  - demooperators/status
  verbs:
  - get
  - patch
  - update
