apiVersion: v1
kind: Service
metadata:
  name: mongoapp-service
spec:
  selector:
    app: mongoapp
  type: LoadBalancer  
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30000
